services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.php.ini:/usr/local/etc/php/conf.d/custom.php.ini
      - ./docker/timezone/${TIMEZONE}:/etc/localtime
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/timezone/${TIMEZONE}:/etc/localtime
    depends_on:
      - php
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./docker/timezone/${TIMEZONE}:/etc/localtime
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGTZ=${TIMEZONE}
    restart: unless-stopped

volumes:
  postgresdata:
